name: svg_path_transform
description: Pure dart library for parsing and manipulating SVG paths, such as rotating, translating, etc.
version: 1.1.4
repository: https://github.com/bramp/svg_path

funding:
  - https://www.buymeacoffee.com/bramp

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.10.0
  path_parsing: ^1.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
