name: svg_path
description: Library for manipulating SVG paths
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-116.0.dev

# Add regular dependencies here.
dependencies:
  meta: ^1.11.0
  path_parsing: ^1.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
