name: svg_path
description: Library for manipulating SVG paths
version: 1.0.0
# repository: https://github.com/my_org/my_repo

funding:
  - https://www.buymeacoffee.com/bramp

environment:
  sdk: ">=3.2.6 <4.0.0"

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  meta: ^1.10.0
  path_parsing: ^1.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
